<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SampleDataSeeder extends Seeder
{
    public function run(): void
    {
        // Insert users
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Provider One',
                'email' => 'provider1@example.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'role' => 'provider',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Consumer One',
                'email' => 'consumer1@example.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'role' => 'consumer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Admin One',
                'email' => 'admin1@example.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Provider Two',
                'email' => 'provider2@example.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'role' => 'provider',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Insert categories
        DB::table('categories')->insert([
            [
                'id' => 1,
                'label' => 'Books',
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'label' => 'Movies',
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'label' => 'Music',
                'provider_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'label' => 'Games',
                'provider_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'label' => 'Vinyles',
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'label' => 'BD / Mangas',
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'label' => 'Montres',
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'label' => 'Art et Posters',
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Insert items
        DB::table('items')->insert([
            // Fournisseur 1 / Utilisateur 2
            [
                'id' => 1,
                'title' => 'The Great Gatsby',
                'description' => 'A classic novel by F. Scott Fitzgerald.',
                'rating' => 5,
                'condition' => 'New',
                'user_id' => 2,
                'category_id' => 1,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'Inception',
                'description' => 'A mind-bending sci-fi movie.',
                'rating' => 4,
                'condition' => 'Good',
                'user_id' => 2,
                'category_id' => 2,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => '1984',
                'description' => 'Dystopian novel by George Orwell.',
                'rating' => 4,
                'condition' => 'Used',
                'user_id' => 2,
                'category_id' => 1,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Fournisseur 4 / Utilisateur 3
            [
                'id' => 4,
                'title' => 'Bohemian Rhapsody Album',
                'description' => 'Queen\'s iconic album.',
                'rating' => 5,
                'condition' => 'Excellent',
                'user_id' => 3,
                'category_id' => 3,
                'provider_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'The Witcher 3',
                'description' => 'Epic RPG game.',
                'rating' => 5,
                'condition' => 'Like New',
                'user_id' => 3,
                'category_id' => 4,
                'provider_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'Le Petit Prince',
                'description' => 'Livre de Saint-Exupéry, édition poche.',
                'rating' => 4,
                'condition' => 'Good',
                'user_id' => 3,
                'category_id' => 1,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'title' => 'Pikachu Illustrator',
                'description' => 'Carte Pokémon rare, édition 1999.',
                'rating' => 5,
                'condition' => 'New',
                'user_id' => 3,
                'category_id' => 4,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'title' => 'Dark Side of the Moon',
                'description' => 'Vinyle de Pink Floyd, réédition 2016.',
                'rating' => 5,
                'condition' => 'Excellent',
                'user_id' => 3,
                'category_id' => 5,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'title' => 'Funko Pop - Darth Vader',
                'description' => 'Figurine Star Wars, édition limitée.',
                'rating' => 4,
                'condition' => 'Used',
                'user_id' => 3,
                'category_id' => 3,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'title' => 'One Piece - Tome 1',
                'description' => 'Manga d’Eiichiro Oda, édition originale.',
                'rating' => 5,
                'condition' => 'New',
                'user_id' => 3,
                'category_id' => 6,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Fournisseur 1 / Utilisateur 1
            [
                'id' => 11,
                'title' => 'Rolex Submariner',
                'description' => 'Montre vintage, années 80.',
                'rating' => 5,
                'condition' => 'Excellent',
                'user_id' => 1,
                'category_id' => 7,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'title' => 'Poster Star Wars Episode IV',
                'description' => 'Poster original signé.',
                'rating' => 4,
                'condition' => 'Used',
                'user_id' => 1,
                'category_id' => 8,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'title' => 'Super Mario Bros 3',
                'description' => 'Cartouche NES, édition américaine.',
                'rating' => 4,
                'condition' => 'Good',
                'user_id' => 1,
                'category_id' => 4,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'title' => 'Charizard 1ère édition',
                'description' => 'Carte Pokémon holographique.',
                'rating' => 5,
                'condition' => 'New',
                'user_id' => 1,
                'category_id' => 4,
                'provider_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
